### PR TITLE
Add sync function

### PR DESCRIPTION
**Pull request by stevemao**
In my project I have to use sync function.

### CODE REVIEW

**Comment by stevemao** [comment]
ping @jergason any news on this?

**Comment by stevemao** [comment]
ping

**Comment by jergason** [comment]
Thanks for this pull request. Unfortunately, I'm not looking to add a sync function right now.

**Comment by stevemao** [comment]
This makes it more consistent as all `fs` functions have a sync version.

**Comment by jergason** [comment]
Yup! Just not interested in adding it. Thank you for your effort on it though.

**Comment by niftylettuce** [comment]
You can use this https://github.com/battlejj/recursive-readdir-sync

**Pull request closed without merging**
