### PR TITLE
Return files even if an error occurred

### PR DESCRIPTION
**Pull request by popod**
Add an option to allow returning files even if a fs.stat error occurs.
#42 #35

### CODE REVIEW

**Comment by popod** [comment]
Does my pull request is ok for you ? would you like to merge it ?

**Comment by aymanar** [comment]
When will this change be released?

**Comment by popod** [comment]
I've test my code since 1 month and it works great..

**Comment by popod** [comment]
please merge..

**Comment by popod** [comment]
I think that the feature we want is that recursive-readdir return files that are "ok" in all case. Then, by setting option `forceContinue=true` we don't care about the error and the number of files that thrown error.. we just want the liste of files without error. With this PR, you close all your issues and pending PR.

I you want just correct the symlink error, I think you should add a test to now if the current file is a symlink and if the error code is "ENOENT". I could do an other PR later for this if you want..

**Comment by popod** [comment]
@jergason this feature fit the needs of @kevincaradant and many others ! I think you should merge it in your repo ???

**Comment by jergason** [comment]
@popod I'm happy to revisit this if you handle the objection I specified: continuing on only `ENOENT`. I'm closing this PR but feel free to open another one handling that case specifically.

**Comment by popod** [comment]
@jergason why only for `ENOENT` ? In my case I want that recursive-readdir return the path of all files that throw no error of any kind.. By continuing on only `ENOENT`, this is not what I want..

As I tell you in my last message, I should add another option to handle the `ENOENT` case. And for that I will open an other PR.

Ok for you ?

**Comment by kevincaradant** [comment]
@jergason , Indeed, my issue https://github.com/jergason/recursive-readdir/issues/46 is typically the case where ENOENT is useless. On some files, I get a EPERM error ! :)
I think @popod propose to you a  good idea.

**Pull request closed without merging**
