### PR TITLE
Upgraded minimatch version

### PR DESCRIPTION
**Pull request by woodyrew**
Fixes npm deprecation warning:
> npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

### CODE REVIEW

**Comment by woodyrew** [comment]
This upgrade causes an issue for Node `v0.6` and `v0.8`. Maybe you could do a major version bump and remove support for those Node versions? I think `v10` is end of life now.

**Comment by mrmlnc** [comment]
@woodyrew,

> Happy to merge this if you also update the .travis.yml to remove node 0.6 and 0.8.
> @jergason

**Comment by jergason** [comment]
What he said!

**Comment by woodyrew** [comment]
@jergason, @mrmlnc: Increased engine node version to `v0.10` latest version and removed old `v0.6` and `v0.8` from travis. Also added `v5, v6` and latest node version to travis.

**Comment by blaenk** [comment]
Is a new release scheduled for this?

**Comment by mrmlnc** [comment]
@woodyrew, IMHO:

#### package.json
```json
"engines": {
  "node": ">=0.10.0"
}
```

#### travis.yml

```yml
language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
```

But it's not up to me. @jergason is maintainer.

**Comment by woodyrew** [comment]
### `package.json` - Node version

@mrmlnc I agree, I changed the node version as per your suggestion.

### `travis.yml`

1. With regard to the Travis node versions, I was following the pattern of `v4.x`. but I thought it was worth adding the latest versions of each major version too.
2. I added `node` which equates to the latest release, just in case. For when the next versions is released and `travis.yml`'s not updated.

@mrmlnc I agree with your suggestion but I think `node` should also be included. What do you think @jergason?

I suggest:
```
language: node_js
node_js:
  - "node"
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
```
This removes `iojs` and the minor versions of `v4`.

**Comment by mrmlnc** [comment]
@jergason ping :panda_face:

**Comment by jergason** [comment]
👍

**Comment by woodyrew** [comment]
Thanks :)

**Comment by mrmlnc** [comment]
Left to do `npm publish` :)

**Pull request merged**
